### ISSUE TITLE
Still waiting...

### ISSUE THREAD

**Issue by blackhat-br** [seekintoo/Chimay-Red#1]
We are still waiting for the release...

**Comment by watbulb** [comment]
It's hilarious because the only contributions you (or rather your "we" amount of pawns) have to open source software, is contributing complaints to the authors on how to use their software, or why it hasn't been released.

I'm happy to accept payment for supporting this software, until then, I couldn't give less of a shit.

Good day.

**Comment by blackhat-br** [comment]
we don't need your support or anything from you or from anyone, just waiting to know your lame method.

**Comment by watbulb** [comment]
right because my "lame" method wasn't already completely obvious in my blogpost: http://blog.seekintoo.com/chimay-red.html
