### ISSUE TITLE
How to fix Invalid Syntax?

### ISSUE THREAD

**Issue by Husseo19** [seekintoo/Chimay-Red#4]
# python3 mikrodb.py -v --architectures="x86" --versions="6.34.4,6.39.2"
[+] Downloading NPK x86 image version: Done
[-] Generating offsets for version: Failed
Traceback (most recent call last):
  File "mikrodb.py", line 446, in <module>
    raise SystemExit(main(verbose=is_verbose, architectures=architectures, versions=versions))
  File "mikrodb.py", line 395, in main
    return builder.generate_database()
  File "mikrodb.py", line 378, in generate_database
    self.populate_www_offsets()
  File "mikrodb.py", line 353, in populate_www_offsets
    ropper = MikroROP(firmware_path)
  File "/root/Downloads/Chimay-Red-master/lib/rop.py", line 56, in __init__
    self.rop = ROP([binary])
  File "/root/src/python3-pwntools/pwnlib/rop/rop.py", line 399, in __init__
    self.__load()
  File "/root/src/python3-pwntools/pwnlib/rop/rop.py", line 869, in __load
    cache = self.__cache_load(elf)
  File "/root/src/python3-pwntools/pwnlib/rop/rop.py", line 802, in __cache_load
    gadgets = eval(open(filename).read())
  File "<string>", line 1
    {134556879L: [u'pop ebx', u'pop edi', u'pop ebp', u'ret'], 134544485L: [u'pop ebx', u'pop ebp', u'ret'], 134544486L: [u'pop ebp', u'ret'], 134553831L: [u'add esp, 0x14', u'pop ebx', u'pop ebp', u'ret'], 134513036L: [u'ret'], 134583117L: [u'pop edx', u'pop ebx', u'pop esi', u'pop edi', u'pop ebp', u'ret'], 134553998L: [u'pop esi', u'pop ebp', u'ret'], 134553997L: [u'pop ebx', u'pop esi', u'pop ebp', u'ret'], 134572720L: [u'pop ebx', u'pop ebx', u'pop ebp', u'ret'], 134548978L: [u'leave', u'ret'], 134548975L: [u'add esp, 0x10', u'leave', u'ret'], 134585561L: [u'pop eax', u'pop ebx', u'pop ebp', u'ret'], 134552890L: [u'pop ebx', u'pop esi', u'pop edi', u'pop ebp', u'ret'], 134552891L: [u'pop esi', u'pop edi', u'pop ebp', u'ret'], 134552892L: [u'pop edi', u'pop ebp', u'ret']}
              ^
SyntaxError: invalid syntax

**Comment by watbulb** [comment]
Can you provide any context, like an actual bug report? Because this is not enough information to go off of.

What version of python3 do you have exactly? `python --version`
It would appear to me that you are not running a virtual environment and are also not installing `python3-pwntools` using pip.

The reason why the `SyntaxError` exception is raised is because the python interpreter you are using has encountered a python2 syntax difference, namely in the syntax: `134552892L`. Python3 does not have the `L` long int type anymore. Leading me to beleive this bug is surely related to your environment and python version.

Try running:

1. `python3 -m virtualenv -p python3.6 venv`
2. `source venv/bin/activate`
3. `pip3 install -r requirements.txt`
4. `python3 mikrodb.py -v --architectures="x86" --versions="6.34.4,6.39.2"`

Also ensure you have the absolute latest python version. As of writing this the software works fine with the given commands above.

**Comment by Husseo19** [comment]
thanks for responding so quickly!
Python Version = Python 3.6.6rc1
I installed pwntools using the link from the requirements.txt, but using -e git+URL  instead.
i ran the commands you mentioned, still the same issue! i am running kali
